











members.push({"email": "laaddison74@yahoo.ca","first_name":"Lyn","last_name":"Addison","street_address":"52 elmbank cres", "city":"Ottawa","province":"ON","postal_code":"K2g3p6", "phone_number":"613.851.4438", "date_added":"7/27/2020","admin":false, "verified": false });
members.push({"email": "tbfemoore@gmail.com","first_name":"Tiffany","last_name":"Moore","street_address":"34 Aldgate Cres", "city":"Ottawa","province":"ON","postal_code":"K2J 2G4", "phone_number":"343-543-9270", "date_added":"11/9/2020","admin":false, "verified": false });
members.push({"email": "michael.coulter@sympatico.ca","first_name":"Corinne & Michael","last_name":"Coulter","street_address":"", "city":"Ottawa","province":"ON","postal_code":"", "phone_number":"613-274-0536", "date_added":"7/20/2020","admin":false, "verified": false });
members.push({"email": "lucienne_marseille@yahoo.ca","first_name":"Lucienne","last_name":"Marseille","street_address":"", "city":"Ottawa","province":"ON","postal_code":"", "phone_number":"", "date_added":"1/31/2021","admin":false, "verified": false });
members.push({"email": "alex.sitiugin@gmail.com","first_name":"Oleksandr","last_name":"Sitigin","street_address":"1804 Radway Terrace", "city":"Ottawa","province":"ON","postal_code":"K1C 5J1", "phone_number":"647-338-6182", "date_added":"1/31/2021","admin":false, "verified": false });
members.push({"email": "france_boutet@hotmail.com","first_name":"Boutet","last_name":"France","street_address":"132 Briston Private", "city":"Ottawa","province":"ON","postal_code":"K1G 5P7", "phone_number":"343 550 0589", "date_added":"2/3/2021","admin":false, "verified": false });
members.push({"email": "Alex.C.Johnson@outlook.com","first_name":"Alex","last_name":"Johnson","street_address":"1320 Richmond Rd Apt 721", "city":"Ottawa","province":"ON","postal_code":"K2B 8L3", "phone_number":"613-295-7737", "date_added":"2/5/2021","admin":false, "verified": false });
members.push({"email": "mulahusica@gmail.com","first_name":"Mulachsic","last_name":"Amela","street_address":"607-314 Central Park Dr.", "city":"Ottawa","province":"ON","postal_code":"K2C0R2", "phone_number":"613 617 1560", "date_added":"3/4/2021","admin":false, "verified": false });
members.push({"email": "hilaryseddon@hotmail.ca","first_name":"Hilary","last_name":"Seddon","street_address":"274 Citiplace Drive", "city":"Ottawa","province":"ON","postal_code":"K2E 0A9", "phone_number":"613-854-5823", "date_added":"3/6/2021","admin":false, "verified": false });
members.push({"email": "neetu.sharawat@gmail.com","first_name":"Sharawat","last_name":"Neeru","street_address":"1116-100 Grant Carman drive", "city":"Ottawa","province":"ON","postal_code":"K2E8B8", "phone_number":"613-462-8638", "date_added":"3/7/2021","admin":false, "verified": false });
members.push({"email": "sabrina.rossignol1@hotmail.com","first_name":"Sabrina","last_name":"Rossignol","street_address":"258 Claridge Dr", "city":"Ottawa","province":"ON","postal_code":"K2J 5B9", "phone_number":"819-318-3341", "date_added":"3/10/2021","admin":false, "verified": false });
members.push({"email": "shaolancarol@gmail.com","first_name":"Carol","last_name":"Chen","street_address":"28 Montana Way", "city":"Ottawa","province":"ON","postal_code":"K2J 4M5", "phone_number":"613-618-5938", "date_added":"3/15/2021","admin":false, "verified": false });
members.push({"email": "yunfeng.li.ca@gmail.com","first_name":"Yunfeng","last_name":"Li","street_address":"120 Pinetrail Cres Ottawa", "city":"Ottawa","province":"ON","postal_code":"", "phone_number":"613-235 1421", "date_added":"3/20/2021","admin":false, "verified": false });
members.push({"email": "sentling@gmail.com","first_name":"Sendawt","last_name":"Tling","street_address":"65 silverlace private", "city":"Ottawa","province":"ON","postal_code":"K1T 3Z8", "phone_number":"613-668-58264", "date_added":"4/3/2021","admin":false, "verified": false });
members.push({"email": "timhoo@gmail.com","first_name":"Tim","last_name":"Hooper","street_address":"304 Tivoli Pvt", "city":"Ottawa","province":"ON","postal_code":"", "phone_number":"613-255-0567", "date_added":"4/12/2021","admin":false, "verified": false });
members.push({"email": "alex.isch2200@gmail.com","first_name":"Alex","last_name":"Isch","street_address":"140 Corinth Private", "city":"Ottawa","province":"ON","postal_code":"K2E 0A8", "phone_number":"613-996-9810", "date_added":"4/13/2021","admin":false, "verified": false });
members.push({"email": "musafirinova@yahoo.com","first_name":"Charlotte","last_name":"Mwajuma","street_address":"216-263 Viewmount Road", "city":"Ottawa","province":"ON","postal_code":"", "phone_number":"613 410 2072", "date_added":"4/14/2021","admin":false, "verified": false });
members.push({"email": "pohchoocraig@gmail.com","first_name":"Poh Choo","last_name":"Low","street_address":"508-1041 Wellington St W", "city":"Ottawa","province":"ON","postal_code":"K1Y 4K8", "phone_number":"6138690765", "date_added":"4/14/2021","admin":false, "verified": false });
members.push({"email": "ranianaoum01@gmail.com","first_name":"Rania","last_name":"Naoum","street_address":"15 Coach House Gate", "city":"Ottawa","province":"ON","postal_code":"K2E 7N", "phone_number":"613-404-9556", "date_added":"4/15/2021","admin":false, "verified": false });
members.push({"email": "rebecca.conrod@gmail.com","first_name":"Becca","last_name":"Conrod","street_address":"18 Gillespie Crescent", "city":"Ottawa","province":"ON","postal_code":"", "phone_number":"613-818-9941", "date_added":"4/16/2021","admin":false, "verified": false });
members.push({"email": "kmcphee76@gmail.com","first_name":"Kara","last_name":"Mcphee","street_address":"38 barnstone drive nepean ", "city":"Ottawa","province":"ON","postal_code":"", "phone_number":"613-914-4021", "date_added":"4/18/2021","admin":false, "verified": false });
members.push({"email": "lynda.manser@icloud.com","first_name":"Lynda","last_name":"Manser","street_address":"10-244 Charlotte", "city":"Ottawa","province":"ON","postal_code":"", "phone_number":"613-875-3772", "date_added":"4/22/2021","admin":false, "verified": false });
members.push({"email": "sovutht@gmail.com","first_name":"Sovuth","last_name":"Try","street_address":"7 mcmurdo court nepean", "city":"Ottawa","province":"ON","postal_code":"k2e5v8", "phone_number":"613-852-8658", "date_added":"4/23/2021","admin":false, "verified": false });
members.push({"email": "ruebendevries@gmail.com","first_name":"Rueben","last_name":"De Vries","street_address":"1339 Meadowlands Dr E", "city":"Ottawa","province":"ON","postal_code":"K2E 7B4", "phone_number":"613-898-5024", "date_added":"4/23/2021","admin":false, "verified": false });
members.push({"email": "diane.leblanc13@gmail.com","first_name":"LeBlanc","last_name":"Diane","street_address":"106-265 Viewmount Drive", "city":"Ottawa","province":"ON","postal_code":"K2E 7E7", "phone_number":"613-981-1103", "date_added":"4/25/2021","admin":false, "verified": false });
members.push({"email": "hazelgabe@protonmail.com","first_name":"Hazel","last_name":"Gabe","street_address":"8-600 Laurier Ave W", "city":"Ottawa","province":"ON","postal_code":"K1R6L1", "phone_number":"613-323-4908", "date_added":"4/25/2021","admin":false, "verified": false });
members.push({"email": "gswhitman44@gmail.com","first_name":"Glenn","last_name":"Whitman","street_address":"19 Fieldberry Private", "city":"Ottawa","province":"ON","postal_code":"K2J 5E7", "phone_number":"343 997 2100", "date_added":"4/28/2021","admin":false, "verified": false });
members.push({"email": "sukster7@yahoo.com","first_name":"Kim","last_name":"Suk-hee","street_address":"29 Kane Terrace ", "city":"Ottawa","province":"ON","postal_code":"K2J 2A5", "phone_number":"613-596-3060", "date_added":"4/30/2021","admin":false, "verified": false });
members.push({"email": "lisa.dowling@live.ca","first_name":"Lisa","last_name":"Dowling","street_address":"20 Chesterton Drive Apt 607", "city":"Ottawa","province":"ON","postal_code":"K2E 6Z7", "phone_number":"613.862.2384", "date_added":"5/13/2021","admin":false, "verified": false });
members.push({"email": "mailtomisba@gmail.com","first_name":"Misbahul","last_name":"Islam","street_address":"1516 Fisher Ave", "city":"Ottawa","province":"ON","postal_code":"K2C 3J5", "phone_number":"613-225-4131", "date_added":"5/18/2021","admin":false, "verified": false });
members.push({"email": "thaobong2801@gmail.com","first_name":"Thao","last_name":"Hoang","street_address":"390 Viewmount Dr", "city":"Ottawa","province":"ON","postal_code":"", "phone_number":"613-981-7864", "date_added":"5/26/2021","admin":false, "verified": false });
members.push({"email": "jay.logan@gmail.com","first_name":"Logan","last_name":"Jay","street_address":"1E Castlebrook Lane", "city":"Ottawa","province":"ON","postal_code":"K2G 5E4", "phone_number":"613-884-3328", "date_added":"5/27/2021","admin":false, "verified": false });
members.push({"email": "re.greenan@gmail.com","first_name":"Rebecca","last_name":"Greenan","street_address":"22 Bowhill Ave", "city":"Ottawa","province":"ON","postal_code":"K2E 6S7", "phone_number":"613-295-8400", "date_added":"5/28/2021","admin":false, "verified": false });
members.push({"email": "abc_daycare@rogers.com","first_name":"Brenda","last_name":"Maheral","street_address":"1109-330 Titan Pvt.", "city":"Ottawa","province":"ON","postal_code":"K2G1E3", "phone_number":"613-276-3459", "date_added":"6/3/2021","admin":false, "verified": false });
members.push({"email": "adrian_pca@yahoo.ca","first_name":"Popescu","last_name":"Adrian","street_address":"336 Gotham Private", "city":"Ottawa","province":"ON","postal_code":"K2C 4G7", "phone_number":"819-230-1638", "date_added":"6/15/2021","admin":false, "verified": false });
members.push({"email": "ihor_ok@hotmail.com","first_name":"Okhrymchuk","last_name":"Ihor","street_address":"27 cleadon drive", "city":"Ottawa","province":"ON","postal_code":"", "phone_number":"613-325-3903", "date_added":"6/21/2021","admin":false, "verified": false });
members.push({"email": "jprevost755@hotmail.com","first_name":"Prevost","last_name":"Jerome","street_address":"222B Claridge Drive", "city":"Ottawa","province":"ON","postal_code":"K2J 5G8", "phone_number":"343 540 9857", "date_added":"6/25/2021","admin":false, "verified": false });
members.push({"email": "mawitea@gmail.com","first_name":"Mawite","last_name":"Lal","street_address":"802-1917 St. Laurent Blvd", "city":"Ottawa","province":"ON","postal_code":"K1G3R9", "phone_number":"5875850631", "date_added":"6/25/2021","admin":false, "verified": false });
members.push({"email": "chehibiadbelkrim@hotmail.com","first_name":"Abdelkrim","last_name":"Chebihi","street_address":"1C Europa Private", "city":"Ottawa","province":"ON","postal_code":"K2E7R5", "phone_number":"819-598-7995", "date_added":"7/1/2021","admin":false, "verified": false });
members.push({"email": "waltersmarcia5@gmail.com","first_name":"Marcia","last_name":"Beeftin","street_address":"Unit 700-2100 Scott street", "city":"Ottawa","province":"ON","postal_code":"K1Z 1A 3", "phone_number":"613-796-5636", "date_added":"7/9/2021","admin":false, "verified": false });
members.push({"email": "lhall@chandos.com","first_name":"Hall","last_name":"Lauren","street_address":"275 Stroget Pvt", "city":"Ottawa","province":"ON","postal_code":"", "phone_number":"613-447-9547", "date_added":"7/12/2021","admin":false, "verified": false });
members.push({"email": "trasteverino55@gmail.com","first_name":"Miller","last_name":"Hugh Edmund","street_address":"1089 Borden Side Rd", "city":"Ottawa","province":"ON","postal_code":"K2C 3P3", "phone_number":"773-510-8147", "date_added":"7/24/2021","admin":false, "verified": false });
members.push({"email": "nguyenalisa1@gmail.com","first_name":"Alisa","last_name":"Greenwood-Nguyen","street_address":"209 Stroget Private", "city":"Ottawa","province":"ON","postal_code":"", "phone_number":"(902) 385 3939", "date_added":"7/27/2021","admin":false, "verified": false });
members.push({"email": "akerandi@gmail.com","first_name":"Andrew","last_name":"Kerandi","street_address":"132 Mangrove Cres", "city":"Ottawa","province":"ON","postal_code":"K1T 0E4", "phone_number":"613-282-1412", "date_added":"8/9/2021","admin":false, "verified": false });
members.push({"email": "surkhay1@hotmail.com","first_name":"Surkhay","last_name":"Musayev","street_address":"9-811 Connaught Ave", "city":"Ottawa","province":"ON","postal_code":"K2B 8K3", "phone_number":"7808841273", "date_added":"8/9/2021","admin":false, "verified": false });
members.push({"email": "susanwhiteley@hotmail.com","first_name":"Susan","last_name":"Whiteley","street_address":"505 - 236 Richmond Road", "city":"Ottawa","province":"ON","postal_code":"k1z6w6", "phone_number":"613:805-0077", "date_added":"8/15/2021","admin":false, "verified": false });
members.push({"email": "rjfaragh@icloud.com","first_name":"Robert","last_name":"Faragher","street_address":"26 Rosetta ave", "city":"Ottawa","province":"ON","postal_code":"", "phone_number":"6138626181", "date_added":"8/20/2021","admin":false, "verified": false });
members.push({"email": "claudrodr@gmail.com","first_name":"Claudio","last_name":"Rodrigues","street_address":"56 Rideau Heights Dr", "city":"Ottawa","province":"ON","postal_code":" K2E 7A6", "phone_number":"613-8512374", "date_added":"9/6/2021","admin":false, "verified": false });
members.push({"email": "Diego.lemem@gmail.com","first_name":"Diego","last_name":"Leme","street_address":"225 Fergus Crescent", "city":"Ottawa","province":"ON","postal_code":"K2J 3L7", "phone_number":"613-6121517", "date_added":"9/6/2021","admin":false, "verified": false });




members.push({"email": "ping99ca@yahoo.ca","first_name":"Baoshun & Guirong","last_name":"Ji","street_address":"6133016727", "city":"Ottawa","province":"ON","postal_code":"", "phone_number":"6133016727", "date_added":"10/17/2021","admin":false, "verified": false });
members.push({"email": "dimo.k.dimitrov@gmail.com","first_name":"Dimo","last_name":"Dimitrov","street_address":"190 Clearview Avenue", "city":"Ottawa","province":"ON","postal_code":"K1Z1B8", "phone_number":"613 290-6181", "date_added":"10/24/2021","admin":false, "verified": false });
members.push({"email": "kuang_ca@yahoo.ca","first_name":"Kuang","last_name":"James","street_address":"36 Westpointe Cres", "city":"Ottawa","province":"ON","postal_code":"K2G 5Y9 ON", "phone_number":"343 883-8683", "date_added":"11/13/2021","admin":false, "verified": false });
members.push({"email": "jfstevenson@outlook.com","first_name":"Stevenson","last_name":"James","street_address":"10E Europa Pvt.", "city":"Ottawa","province":"ON","postal_code":"", "phone_number":"613-297-3758", "date_added":"12/1/2021","admin":false, "verified": false });
members.push({"email": "habon_@hotmail.com","first_name":"Habon","last_name":"Assoweh","street_address":"923 Whiteford Way", "city":"Ottawa","province":"ON","postal_code":"", "phone_number":"613-462-1472", "date_added":"12/19/2021","admin":false, "verified": false });
members.push({"email": "april.liu.statistics@gmail.com","first_name":"April","last_name":"liu","street_address":"604 Dundonald Dr", "city":"Ottawa","province":"ON","postal_code":" K2J 5Y8", "phone_number":"3067162371", "date_added":"1/6/2022","admin":false, "verified": false });
members.push({"email": "pdmdragon62@gmail.com","first_name":"Peter","last_name":"Murphy","street_address":"29 Estelle Crs Nepean", "city":"Ottawa","province":"ON","postal_code":"K2H5W9", "phone_number":"613 316 0502", "date_added":"1/6/2022","admin":false, "verified": false });
members.push({"email": "cpeabody@storm.ca","first_name":"Coray","last_name":"Peabody","street_address":"18 Northview road", "city":"Ottawa","province":"ON","postal_code":"", "phone_number":"6137627313", "date_added":"1/20/2022","admin":false, "verified": false });
members.push({"email": "ahmed_muhawesh@hotmail.com","first_name":"Ahmed","last_name":"Muhawesh","street_address":"154 Craig Henry drive", "city":"Ottawa","province":"ON","postal_code":"", "phone_number":"613-700-8118", "date_added":"2/2/2022","admin":false, "verified": false });
members.push({"email": "hani.jabbour@app8pay.com","first_name":"Hani & Ruba","last_name":"Jabbour","street_address":"120 Cartier Street", "city":"Ottawa","province":"ON","postal_code":"", "phone_number":"613-265-0533", "date_added":"2/14/2022","admin":false, "verified": false });
members.push({"email": "hello@thissplendidchaos.ca","first_name":"Kelly","last_name":"Manweiler","street_address":"27 Overlake Drive", "city":"Ottawa","province":"ON","postal_code":"", "phone_number":"6138622231", "date_added":"2/4/2022","admin":false, "verified": false });
members.push({"email": "irene.1978@yahoo.com","first_name":"Irene","last_name":"Caowat","street_address":"28-2610 Draper Ave. Ottawa", "city":"Ottawa","province":"ON","postal_code":"", "phone_number":"613-316-7111", "date_added":"2/4/2022","admin":false, "verified": false });
members.push({"email": "hollyhope70@hotmail.ca","first_name":"Blair","last_name":"Holly","street_address":"2 Bertona Unit 34", "city":"Ottawa","province":"ON","postal_code":"", "phone_number":"613 2975114", "date_added":"2/10/2022","admin":false, "verified": false });
members.push({"email": "mitziross@rogers.com","first_name":"Ross","last_name":"Mitzi","street_address":"405 Viewmount Drive", "city":"Ottawa","province":"ON","postal_code":"K2E 7P1", "phone_number":"613-225-5105", "date_added":"2/10/2022","admin":false, "verified": false });
members.push({"email": "kattrines@gmail.com","first_name":"Kathryn","last_name":"Trines","street_address":"4 Willwood cres", "city":"Ottawa","province":"ON","postal_code":"K2J 4B2", "phone_number":"613-790-1186", "date_added":"2/10/2022","admin":false, "verified": false });
members.push({"email": "laurent.frerebeau@free.fr","first_name":"Laurent","last_name":"Frerebeau","street_address":"176 Cumberland Street", "city":"Ottawa","province":"ON","postal_code":"K1N 7H1", "phone_number":"613-255-0081", "date_added":"2/11/2022","admin":false, "verified": false });
members.push({"email": "santamaxime@gmail.com","first_name":"Jean","last_name":"Grosseau","street_address":"717-45 HOLLAND AVE ", "city":"Ottawa","province":"ON","postal_code":"K1Y 4S3", "phone_number":"438 493 1116", "date_added":"2/19/2022","admin":false, "verified": false });
members.push({"email": "christine.dingley@gmail.com","first_name":"Chris","last_name":"Dingley","street_address":"611-1310 McWatters Road", "city":"Ottawa","province":"ON","postal_code":"K2C 3N8", "phone_number":"613-859-8758", "date_added":"2/26/2022","admin":false, "verified": false });
members.push({"email": "joshua.larocque@gmail.com","first_name":"LaRocque","last_name":"Josh","street_address":"115 Tower Road", "city":"Ottawa","province":"ON","postal_code":"K2G2G1", "phone_number":"6132619885", "date_added":"2/26/2022","admin":false, "verified": false });
members.push({"email": "shuqjing@gmail.com","first_name":"Jing","last_name":"Shuquan","street_address":"668 Gainsborough Avenue", "city":"Ottawa","province":"ON","postal_code":"K2A 2Z1", "phone_number":"613 808 2208", "date_added":"3/11/2022","admin":false, "verified": false });
members.push({"email": "donata.john1@gmail.com","first_name":"Donata","last_name":"john","street_address":"1980 Rolling Brook Dr. Gloucester", "city":"Ottawa","province":"ON","postal_code":"", "phone_number":"613-316-8771", "date_added":"3/17/2022","admin":false, "verified": false });
members.push({"email": "carolynpollock@rogers.com","first_name":"Carolyn","last_name":"Pollock","street_address":"1558 Commodore Dr.", "city":"Ottawa","province":"ON","postal_code":"K0A 2E0", "phone_number":"613-489-2658", "date_added":"3/18/2022","admin":false, "verified": false });
members.push({"email": "maodixox@gmail.com","first_name":"Florence","last_name":"Fung","street_address":"404-212 Viewmount", "city":"Ottawa","province":"ON","postal_code":"", "phone_number":"8732880784", "date_added":"3/11/2022","admin":false, "verified": false });
members.push({"email": "coffeyclare@gmail.com","first_name":"Coffey","last_name":"Clare","street_address":"105-1124 Meadowlands Dr", "city":"Ottawa","province":"ON","postal_code":"K2E 6H9", "phone_number":"343-574-9100", "date_added":"3/26/2022","admin":false, "verified": false });
members.push({"email": "windy88911@gmail.com","first_name":"Wang","last_name":"Han","street_address":"28 Argue Dr", "city":"Ottawa","province":"ON","postal_code":"", "phone_number":"613-630-0911.", "date_added":"3/30/2022","admin":false, "verified": false });
members.push({"email": "John_li99@hotmail.com","first_name":"Lily","last_name":"Han","street_address":"122 Umbra Plance", "city":"Ottawa","province":"ON","postal_code":"", "phone_number":"613 4103870", "date_added":"4/4/2022","admin":false, "verified": false });
members.push({"email": "darleneyee@rogers.com","first_name":"Darlene","last_name":"Yee","street_address":"383 Citiplace Dr", "city":"Ottawa","province":"ON","postal_code":"K2E 0A7", "phone_number":"613-806-8771", "date_added":"4/7/2022","admin":false, "verified": false });
members.push({"email": "shawnacasement@gmail.com","first_name":"Shawna","last_name":"Casement","street_address":"292 Briston Pvt", "city":"Ottawa","province":"ON","postal_code":"", "phone_number":"613-229-4885", "date_added":"4/23/2022","admin":false, "verified": false });
members.push({"email": "ogrodnik825@gmail.com","first_name":"Lucie","last_name":"Ogrodnik","street_address":"420 Berkley Avenue", "city":"Ottawa","province":"ON","postal_code":"", "phone_number":"613-825-6994", "date_added":"4/23/2022","admin":false, "verified": false });
members.push({"email": "429798399@qq.com","first_name":"Yanyan","last_name":"Qu","street_address":"812-20 chesterton Dr ", "city":"Ottawa","province":"ON","postal_code":"K2E 6Z7", "phone_number":"613-262-5110", "date_added":"4/24/2022","admin":false, "verified": false });
members.push({"email": "jasonanthonysmith87@gmail.com","first_name":"Jason","last_name":"Smith","street_address":"18 Newbury Avenue", "city":"Ottawa","province":"ON","postal_code":"", "phone_number":"343-999-2386", "date_added":"4/24/2022","admin":false, "verified": false });
members.push({"email": "bripetersen18@gmail.com","first_name":"Briana","last_name":"Petersen","street_address":"1284 Hammond Street", "city":"Ottawa","province":"ON","postal_code":"", "phone_number":"9058071832", "date_added":"4/25/2022","admin":false, "verified": false });
members.push({"email": "saba.jasarevic@gmail.com","first_name":"Saba","last_name":"Jasarevic","street_address":"674 MALIBU TERR", "city":"Ottawa","province":"ON","postal_code":"", "phone_number":"6132289209", "date_added":"4/27/2022","admin":false, "verified": false });
members.push({"email": "molly86865@outlook.com","first_name":"xiuqing","last_name":"Zhan","street_address":"402 nittany Crescent", "city":"Ottawa","province":"ON","postal_code":"", "phone_number":"6134026288", "date_added":"4/28/2022","admin":false, "verified": false });
members.push({"email": "conrad.bonifacio@gmail.com","first_name":"Conrad","last_name":"Bonifacio","street_address":"57 Crystal Park Cres", "city":"Ottawa","province":"ON","postal_code":"K2C 4A3", "phone_number":"6138780612", "date_added":"4/29/2022","admin":false, "verified": false });
members.push({"email": "janice_willson1969@yahoo.ca","first_name":"Janice","last_name":"Willson","street_address":"7-2087 Baseline Road", "city":"Ottawa","province":"ON","postal_code":"", "phone_number":"613.252.6299", "date_added":"5/2/2022","admin":false, "verified": false });
members.push({"email": "leajanhu@gmail.com","first_name":"Lea","last_name":"Martonfi","street_address":"120 Grant Carman Drive #209 ", "city":"Ottawa","province":"ON","postal_code":"K2E1C8", "phone_number":"9055061210", "date_added":"5/3/2022","admin":false, "verified": false });
members.push({"email": "bszirtes@gmail.com","first_name":"Carolyn","last_name":"McGregor","street_address":"320- 1170 Fisher Avenue", "city":"Ottawa","province":"ON","postal_code":"", "phone_number":"(613) 728 - 6693", "date_added":"5/4/2022","admin":false, "verified": false });
members.push({"email": "canstarzy@protonmail.com","first_name":"Henry","last_name":"Starzynski","street_address":"3 Kesler Ave", "city":"Ottawa","province":"ON","postal_code":"", "phone_number":"613-720-7723", "date_added":"5/5/2022","admin":false, "verified": false });
members.push({"email": "nlalu44@hotmail.com","first_name":"Nirannanilathu","last_name":"Lalu","street_address":"711 - 100 Carman Drive", "city":"Ottawa","province":"ON","postal_code":"", "phone_number":"343 984 1749", "date_added":"5/15/2022","admin":false, "verified": false });
members.push({"email": "rachel.weatherbee@gmail.com","first_name":"Rachel","last_name":"Weatherbee","street_address":"6 Hendricus Private", "city":"Ottawa","province":"ON","postal_code":"", "phone_number":"6132768719", "date_added":"5/16/2022","admin":false, "verified": false });
members.push({"email": "larry.feng@cibc.com","first_name":"Larry","last_name":"Feng","street_address":"328 Rosina way. ", "city":"Ottawa","province":"ON","postal_code":"", "phone_number":"613-287-1660", "date_added":"5/18/2022","admin":false, "verified": false });
members.push({"email": "E4Robertson@gmail.com","first_name":"Elizabeth","last_name":"Robertson","street_address":"304-78 Hinton Ave. N.", "city":"Ottawa","province":"ON","postal_code":"", "phone_number":"5195885274", "date_added":"5/24/2022","admin":false, "verified": false });
members.push({"email": "jb23_82@msn.com","first_name":"Janice","last_name":"Brillinger","street_address":"#309-1170 Fisher Ave", "city":"Ottawa","province":"ON","postal_code":"", "phone_number":"613-526-5956", "date_added":"5/26/2022","admin":false, "verified": false });
members.push({"email": "gorospemarkisrael@yahoo.com.ph","first_name":"Mark israel","last_name":"Gorospe","street_address":"615-2700 saratoga place", "city":"Ottawa","province":"ON","postal_code":"", "phone_number":"6133149238", "date_added":"5/28/2022","admin":false, "verified": false });
members.push({"email": "davebed2@hotmail.com","first_name":"David","last_name":"Bedard","street_address":"1343 Meadowlands Dr East Apt 408", "city":"Ottawa","province":"ON","postal_code":"", "phone_number":"8733548700", "date_added":"5/29/2022","admin":false, "verified": false });
members.push({"email": "salata3@hotmail.com","first_name":"Habi","last_name":"Jabbour","street_address":"120 Cartier street", "city":"Ottawa","province":"ON","postal_code":"", "phone_number":"6132656869", "date_added":"5/30/2022","admin":false, "verified": false });
members.push({"email": "shahpar.azadi@gmail.com","first_name":"Shahpar","last_name":"Akhondzadeh","street_address":"1505 Baseline road", "city":"Ottawa","province":"ON","postal_code":"", "phone_number":"3435581816", "date_added":"6/11/2022","admin":false, "verified": false });